### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ogu2** [flowbased/protocol-examples#1]
Could you please provide documentation on how to link up the protocol with the noflo UI.
What, for example is the USER_UUID?
Thanks

**Comment by jonnor** [comment]
```
Load app.flowhub.io
Click “Login” and connect Flowhub with your TheGrid account
Click “Settings” and take note of your User Identifier
```

http://docs.flowhub.io/getting-started-node/

**Comment by jonnor** [comment]
Hopefully we'll get rid of the neccesity of doing that manually, up-front soon, by letting Flowhub handle the registrations with a live-mode like URL.
